#!/usr/bin/env node
// Generate _site/analytics/index.html — the roadmap group's charts page.
//
// It opens with Cost (per-agent token and dollar spend), which lived on the
// roadmap page for its first few hours before the nav restructure gave the
// charts a page of their own (@jwildfire, 2026-07-25). Further charts are meant
// to land here as sections beside it rather than back on the roadmap.
//
// Unlike the rest of the site, the data here is not an API read: it is built from
// @jwildfire's local Claude Code transcripts and committed. See the section's own
// footnote, or scripts/build_usage_data.py.
import fs from 'node:fs/promises';
import path from 'node:path';

import { ROOT, HUB } from './lib/repos.mjs';
import { siteHeader } from './lib/nav.mjs';
import { usageSection } from './lib/usage/render.mjs';

const OUT_DIR = path.join(ROOT, '_site', 'analytics');

// A missing data file renders the section's own "not generated yet" notice — the
// page still builds, because the deploy cannot produce this data itself.
let usage = null;
try {
  usage = JSON.parse(await fs.readFile(path.join(ROOT, 'site', 'usage', 'usage.json'), 'utf8'));
} catch {
  console.warn('analytics: site/usage/usage.json missing — rendering the empty-state notice');
}

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Analytics · obot</title>
<link rel="stylesheet" href="../assets/styles.css">
</head>
<body class="wide">
${siteHeader({ page: 'analytics', depth: 1 })}

<h1>Analytics</h1>
<p class="tagline">Charts about how this portfolio gets built. Starting with what it costs;
more will land here beside it.</p>

${usageSection(usage)}

<footer class="site">Generated by
<a href="https://github.com/${HUB}/blob/main/scripts/build_analytics.mjs"><code>build_analytics.mjs</code></a>
· regenerates via <code>deploy-site.yml</code>.</footer>
</body>
</html>
`;

await fs.mkdir(OUT_DIR, { recursive: true });
await fs.writeFile(path.join(OUT_DIR, 'index.html'), html);

console.log(usage
  ? `analytics: cost section — $${usage.totals.cost} over ${usage.totals.activeDays} active days, ${usage.totals.agents} agents`
  : 'analytics: cost section — no usage data committed');
