#!/usr/bin/env node
// Writes the IDs from reports/decisions/registry.json onto the decision pages.
//
//   node scripts/stamp_decision_ids.mjs           # stamp every artifact
//   node scripts/stamp_decision_ids.mjs --check   # fail if any page is out of date
//
// Each page gets `<meta name="decision-id">` in its head and, right under the title,
// a key listing every question with its canonical ID, the artifact's own original
// code beside it, and the question in words. The block sits between HTML comment
// markers and is regenerated in place, so editing the registry and re-running is the
// only way it changes — nothing here is hand-maintained.
//
// The key is added rather than the codes being rewritten in the prose: the pages are
// twelve different hand-built documents, and their sentences ("if only two get
// answered, make them A1 and A2") are @jwildfire's reading material. The ID is a
// handle, not a replacement for the sentence that says what is being decided.
import fs from 'node:fs';
import path from 'node:path';

import { ROOT } from './lib/repos.mjs';
import { readRegistry } from './lib/decision-ids.mjs';

const BEGIN = '<!-- BEGIN decision-ids — generated by scripts/stamp_decision_ids.mjs from reports/decisions/registry.json; do not hand-edit -->';
const END = '<!-- END decision-ids -->';
const check = process.argv.includes('--check');

const esc = (s = '') => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// currentColor throughout: these twelve pages each carry their own palette, and a
// hardcoded ink or paper colour would look pasted-on in at least one of them.
const STYLE = `<style>
.decision-ids { margin: 1.1rem 0 1.4rem; padding: .8rem 1rem .85rem; border: 1px solid color-mix(in srgb, currentColor 22%, transparent); border-radius: 9px; font-size: .92rem; line-height: 1.5; }
.decision-ids > p { margin: 0 0 .55rem; font-size: .72rem; letter-spacing: .07em; text-transform: uppercase; opacity: .62; font-weight: 600; }
.decision-ids ol { list-style: none; margin: 0; padding: 0; }
.decision-ids li { margin: .32rem 0; display: flex; flex-wrap: wrap; gap: .4rem; align-items: baseline; }
.decision-ids a.did { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-weight: 700; text-decoration: none; white-space: nowrap; border-bottom: 1px dotted currentColor; }
.decision-ids .dcode { font-size: .78em; opacity: .55; white-space: nowrap; }
.decision-ids .dq { flex: 1 1 14rem; min-width: 0; }
@media (max-width: 460px) { .decision-ids .dq { flex-basis: 100%; } }
</style>`;

function block(a) {
  const rows = a.questions.map((q) => `  <li id="${q.id}"><a class="did" href="#${q.id}">${q.id}</a><span class="dcode">${esc(q.code)}</span><span class="dq">${esc(q.question)}</span></li>`).join('\n');
  return `${BEGIN}
${STYLE}
<aside class="decision-ids" id="${a.id}">
<p>${a.id} · quote an ID below when you decide</p>
<ol>
${rows}
</ol>
</aside>
${END}`;
}

const reg = readRegistry();
let changed = 0;
const stale = [];

for (const a of reg.artifacts) {
  const file = path.join(ROOT, 'reports', 'decisions', a.slug, 'index.html');
  let html = fs.readFileSync(file, 'utf8');
  const before = html;

  const meta = `<meta name="decision-id" content="${a.id}">`;
  if (/<meta\s+name=["']decision-id["'][^>]*>/i.test(html)) {
    html = html.replace(/<meta\s+name=["']decision-id["'][^>]*>/i, meta);
  } else if (/<meta\s+name=["']description["'][^>]*>\n?/i.test(html)) {
    html = html.replace(/(<meta\s+name=["']description["'][^>]*>)/i, `$1\n${meta}`);
  } else {
    html = html.replace(/(<\/title>)/i, `$1\n${meta}`);
  }

  const b = block(a);
  if (html.includes(BEGIN)) {
    html = html.replace(new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')}`), b);
  } else if (/<\/h1>/i.test(html)) {
    // After the title, before the argument — the ID is the first thing on the page
    // after what the page is called.
    html = html.replace(/(<\/h1>)/i, `$1\n${b}`);
  } else {
    console.error(`${a.slug}: no <h1> to anchor the ID key to — add one, or place the block by hand`);
    process.exitCode = 1;
    continue;
  }

  if (html === before) continue;
  if (check) { stale.push(`${a.id} — reports/decisions/${a.slug}/index.html`); continue; }
  fs.writeFileSync(file, html);
  changed += 1;
}

// The decisions landing page is NOT stamped here. It used to be a hand-kept list
// that had drifted to two of twelve cards, so this script patched an id into each
// card it found. scripts/build_decisions.mjs now regenerates that page at deploy
// time from the registry, and its committed copy is a declared-stale fallback —
// stamping it would mean --check failing the deploy over a file whose own header
// says to edit the generator instead. The generator reads the same registry, so the
// ids on the published page come from one place either way.

if (check) {
  if (stale.length) {
    console.error('These pages do not match the registry — run node scripts/stamp_decision_ids.mjs:');
    stale.forEach((s) => console.error(`  ${s}`));
    process.exit(1);
  }
  console.log(`decision ids: ${reg.artifacts.length} artifacts in sync with the registry`);
} else {
  const questions = reg.artifacts.reduce((n, a) => n + a.questions.length, 0);
  console.log(`decision ids: stamped ${changed} of ${reg.artifacts.length} artifacts (${questions} questions)`);
}
